### ISSUE TITLE
Type of Sample Weights 

### ISSUE THREAD

**Issue by VasylHafych** [bat/BAT.jl#100]
Currently, the sample weights outputed by BAT are of type `Array{Int64}`. While standard Julia Stats functions require weights type such as (`AnalyticWeights`, `FrequencyWeights`, `ProbabilityWeights`, ...). 
I suggest using `FrequencyWeights` for Metropolis-Hastings and `ProbabilityWeights` for accept/reject sampling.

**Comment by oschulz** [comment]
I've considered this a while ago, but decided against it: The problem is the weird behavior of `...Weights` - it's a special array type of real, instead of representing itself as an array of a weights-type. That would make row-access in `DensitySampleVector` problematic.
