### ISSUE TITLE
Error of iid sampler with a truncated mixture distribution 

### ISSUE THREAD

**Issue by VasylHafych** [bat/BAT.jl#109]
Hi @oschulz,

I found one bug while testing BAT iid sampler. I am not sure if this is a problem of BAT, but if so it might be useful to fix it to be able to test AHMI properly. Here is a code example: 

```julia
using Distributions, BAT, ValueShapes

mixture = MixtureModel(Normal[
   Normal(-1.0, 0.5),
   Normal(1.0, 0.5),],)

dist = product_distribution([truncated(mixture, -2, 2), truncated(Normal(0.0,1.0), -2, 2), ])

iid_distributions = NamedTupleDist(a = dist,)

samples_iid = bat_sample(iid_distributions, 10^5).result; 
```

the error message is 

```terminal
ERROR: MethodError: no method matching iterate(::MixtureModel{Univariate,Continuous,Normal,Float64})
Closest candidates are:
  iterate(::Core.SimpleVector) at essentials.jl:603
  iterate(::Core.SimpleVector, ::Any) at essentials.jl:603
  iterate(::ExponentialBackOff) at error.jl:253
  ...
Stacktrace:
 [1] copyto!(::Array{Float64,1}, ::MixtureModel{Univariate,Continuous,Normal,Float64}) at ./abstractarray.jl:721
 [2] _collect(::UnitRange{Int64}, ::MixtureModel{Univariate,Continuous,Normal,Float64}, ::Base.HasEltype, ::Base.HasLength) at ./array.jl:609
 [3] collect(::MixtureModel{Univariate,Continuous,Normal,Float64}) at ./array.jl:603
```
By the way, MCMC sampling works correctly with this distribution. Only iid sampling of truncated distribution fails .

**Comment by oschulz** [comment]
Sorry for the late reply!

This is technically not a problem in BAT, it's just that BAT relies on `var(dist)` being defined for distributions used as priors. StatsBase defines `var` for `Truncated(Normal(...))` but not for `Truncated` in general (would require numerical integration).

I'm planning to change a few things in BAT so that BAT will use a fall-back in such cases. Until then,
here's a somewhat ugly workaround:

```julia
# Ugly hack, var is not defined for Distributions.Truncated in
# general (only for Normal). This is type piracy!
function Statistics.var(d::Distributions.Truncated)
    rng = Philox4x((0, 0))
    var(rand(rng, d, 10^3))
end
```
