### ISSUE TITLE
Add support for UltraNest

### ISSUE THREAD

**Issue by JohannesBuchner** [bat/BAT.jl#236]
I am just opening this to have a place to track and discuss, no rush.

UltraNest is a general-purpose Bayesian inference library based on nested sampling, documented at https://johannesbuchner.github.io/UltraNest/ 

I think @oschulz's idea was to create a Julia package in a better form than the example Julia script at https://github.com/JohannesBuchner/UltraNest/tree/master/languages/julia . I don't know how Julia packages are distributed.

**Comment by oschulz** [comment]
Yes, I propose we create a registered package UltraNest.jl, as an official wrapper for UltraNest. Then it should be quite easy to add it to BAT as an optional dependency (like we do with Cuba already).

**Comment by oschulz** [comment]
Done.
