### ISSUE TITLE
HMC warmup not implemented correctly?

### ISSUE THREAD

**Issue by cescalara** [bat/BAT.jl#267]
Hi, I was updating some old notebooks and I noticed that in `BAT v2.0.3` the stepsize reached In a simple example of fitting the mean of a Gaussian distribution seems off in comparison with Stan. I had noticed this and fixed it back before the v2 release but it seems to have popped up again (see fig below for a comparison of HMC in BAT and Stan).

I'll try to find time to check this in more detail but just wanted to bring it to your attention. Ideally I could make a CI test for this behaviour - but can at least share my code if someone else has more time.

<img width="895" alt="image" src="https://user-images.githubusercontent.com/23123253/110765500-87138800-8254-11eb-8b54-ad5d6789fb80.png">

**Comment by oschulz** [comment]
Oh, thanks for checking this! It's strange, the improvements you made back then (https://github.com/bat/BAT.jl/pull/191/files) are all still part of BAT, I just checked. So I'm not quite sure what is going on.

**Comment by cescalara** [comment]
Yes, I'll have to take a closer look at what has changed and just wanted to flag it for now. You can assign me if you like.

**Comment by oschulz** [comment]
Merci!

**Comment by cescalara** [comment]
Hi, as discussed today this issue is now resolved taking into account the space transformations and the equivalent warm-up length. I can offer a PR with some tidied-up code and we can discuss further the next changes.

**Comment by oschulz** [comment]
> I can offer a PR with some tidied-up code and we can discuss further the next changes.

That would be great!
