### ISSUE TITLE
Handling periodic parameters

### ISSUE THREAD

**Issue by fredRos** [bat/BAT.jl#340]
I would like to understand how you handle the transformation of periodic parameters like an angle to an unbounded domain internally. Couldn't find any mention in the docs and also couldn't find an example or something in the https://github.com/bat/BAT.jl/blob/main/src/transforms/distribution_transform.jl file but I might have missed that.

Thanks

**Comment by oschulz** [comment]
We haven't had many application in with periodic parameters so far. In principle, using a [Distributions.VonMises](https://juliastats.org/Distributions.jl/latest/univariate/#Distributions.VonMises) distribution should work out-of-the-box. If the prior is weak, the mode may end up split though, I guess. We're currently working on integrating normalizing-flows into BAT's sampling to handle multi-modal posteriors with widely separated modes better.

**Comment by fredRos** [comment]
@oschulz Thanks. I never really thought this through myself, either. But I put some thoughts [here](https://github.com/pypmc/pypmc/issues/98#issuecomment-1088508154). Looks like staying 2D is the better solutions for a sampler that wants a continous unbounded space

**Comment by oschulz** [comment]
> Looks like staying 2D is the better solutions ...

Yes, I've been thinking about this too - in cases where there's no natural 2D representation, maybe one could add a virtual vector length as a dummy parameter, with a Weibull or similar positive prior on it. The likelihood would just ignore that parameter. This should keep the sampler happy and it wouldn't introduce multi-modality.
