### ISSUE TITLE
too strong version req. of dependencies

### ISSUE THREAD

**Issue by 8me** [bat/BAT.jl#400]
I tried to add `BAT.jl` to one of my projects, which was not possible due to a version conflict in the dependencies. After checking the `Project.toml` of `BAT.jl` it seems to me that the required versions are a little bit toooo strong. For every dependency only some specific version numbers are allowed, which seems a little bit over the top?! :thinking:

**Comment by oschulz** [comment]
Hi @8me - sorry for this - we're preparing a BAT.jl v3.0 release, until then, please use BAT#main, not v2.0, which indeed has very outdated deps.

BAT#main currently has two outdated deps itself, Distributions.jl and (indirectly) Static.jl, I hope to resolve that very soon.

**Comment by 8me** [comment]
Ok, thanks :+1:
