### ISSUE TITLE
Eigenfunction Error

### ISSUE THREAD

**Issue by VasylHafych** [bat/BAT.jl#66]
Hi,
Seems like function **[eig()](https://docs.julialang.org/en/v0.6.2/stdlib/linalg/#Base.LinAlg.eig)** has to be replaced with **[eigvals()](https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/index.html)**.
https://github.com/bat/BAT.jl/blob/4e41e73f87cd1755e6ef6e4caa1e64f328ac23f5/src/samplers/mcmc/algorithms/mh_tuner.jl#L108
The first one is crashing tunning cycle and giving an error. 

Vasyl

**Comment by oschulz** [comment]
Thanks!

Fixed in 9055e92 and latest release v0.2.1

**Comment by VasylHafych** [comment]
Thanks!
There is one more function that should be replaced there: 
`eye(length(ev))` with `Matrix{Float64}(I, length(ev), length(ev))`
See here: 
https://github.com/bat/BAT.jl/blob/4e41e73f87cd1755e6ef6e4caa1e64f328ac23f5/src/samplers/mcmc/algorithms/mh_tuner.jl#L111

**Comment by oschulz** [comment]
Thanks for noticing, fixed in 6ad050d.
