### ISSUE TITLE
how to get(build) docs

### ISSUE THREAD

**Issue by IwM341** [bat/BAT.jl#74]
ERROR: Load

Error: `makedocs` encountered an error. Terminating build
[BatDocsBuildProblem.txt](https://github.com/bat/BAT.jl/files/3570862/BatDocsBuildProblem.txt)

**Comment by altavir** [comment]
Please provide more informative message. What you tried to achieve. What did you expect, etc

**Comment by IwM341** [comment]
i try to get a documentation of bat.jl
