### ISSUE TITLE
Tutorial is missing package installation

### ISSUE THREAD

**Issue by altavir** [bat/BAT.jl#93]
The first line here: https://bat.github.io/BAT.jl/dev/tutorial/#Tutorial-1 is failing because some packages are not installed.

**Comment by oschulz** [comment]
Is this with BAT v1.0.1, or the dev-version (master branch)? Which package(s) is/are missing?

**Comment by altavir** [comment]
Packages are there, I mean that there is no instruction about `Pkg.add(...)` and related stuff. Without it, it fails immediately. Since Julia is not that famous, I think it makes sense to add a remark about package installation.

**Comment by oschulz** [comment]
You mean like here? https://bat.github.io/BAT.jl/stable/installation

**Comment by altavir** [comment]
Yeah, I missed this part, only wanted to launch tutorial. Please add a reference to this page to the tutorial, it should cover everything.
